export const GET_ALL_PROMOTION_REQUEST = 'slide/GET_ALL_PROMOTION_REQUEST';
export const GET_ALL_PROMOTION_SUCCESS = 'slide/GET_ALL_PROMOTION_SUCCESS';
export const GET_ALL_PROMOTION_FAILURE = 'slide/GET_ALL_PROMOTION_FAILURE';

//on single product page
export const GET_SINGLE_CONTACT_REQUEST = 'patient/GET_SINGLE_CONTACT_REQUEST';
export const GET_SINGLE_CONTACT_SUCCESS = 'patient/GET_SINGLE_CONTACT_SUCCESS';
export const GET_SINGLE_CONTACT_FAILURE = 'patient/GET_SINGLE_CONTACT_FAILURE';

//used
export const GET_AUTHOR_PRODUCT_REQUEST = 'products/GET_AUTHOR_PRODUCT_REQUEST';
export const GET_AUTHOR_PRODUCT_SUCCESS = 'products/GET_AUTHOR_PRODUCT_SUCCESS';
export const GET_AUTHOR_PRODUCT_FAILURE = 'products/GET_AUTHOR_PRODUCT_FAILURE';


//for admin only
export const ADD_PROMOTION_REQUEST = 'slides/ADD_PROMOTION_REQUEST';
export const ADD_PROMOTION_SUCCESS = 'slides/ADD_PROMOTION_SUCCESS';
export const ADD_PROMOTION_FAILURE = 'slides/ADD_PROMOTION_FAILURE';

//for admin only
export const UPDATE_PATIENTCONTACT_REQUEST = 'products/UPDATE_PATIENTCONTACT_REQUEST';
export const UPDATE_PATIENTCONTACT_SUCCESS = 'products/UPDATE_PATIENTCONTACT_SUCCESS';
export const UPDATE_PATIENTCONTACT_FAILURE = 'products/UPDATE_PATIENTCONTACT_FAILURE';

//for admin only
export const DELETE_PROMOTION_REQUEST = 'products/DELETE_PROMOTION_REQUEST';
export const DELETE_PROMOTION_SUCCESS = 'products/DELETE_PROMOTION_SUCCESS';
export const DELETE_PROMOTION_FAILURE = 'products/DELETE_PROMOTION_FAILURE';

export const DELETE_OPPOINTMENT_REQUEST = 'products/DELETE_OPPOINTMENT_REQUEST';
export const DELETE_OPPOINTMENT_SUCCESS = 'products/DELETE_OPPOINTMENT_SUCCESS';
export const DELETE_OPPOINTMENT_FAILURE = 'products/DELETE_OPPOINTMENT_FAILURE';



export const GET_AUTHOR_PRODUCT_REQUEST1 = 'products/GET_AUTHOR_PRODUCT_REQUEST1';
export const GET_AUTHOR_PRODUCT_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT_SUCCESS2';
export const GET_AUTHOR_PRODUCT_FAILURE3 = 'products/GET_AUTHOR_PRODUCT_FAILURE3';
