export const GET_ALL_PATIENTDETAILS_REQUEST = 'products/GET_ALL_PATIENTDETAILS_REQUEST';
export const GET_ALL_PATIENTDETAILS_SUCCESS = 'products/GET_ALL_PATIENTDETAILS_SUCCESS';
export const GET_ALL_PATIENTDETAILS_FAILURE = 'products/GET_ALL_PATIENTDETAILS_FAILURE';

//on single product page
export const GET_SINGLE_PRODUCT_REQUEST = 'products/GET_SINGLE_PRODUCT_REQUEST';
export const GET_SINGLE_PRODUCT_SUCCESS = 'products/GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAILURE = 'products/GET_SINGLE_PRODUCT_FAILURE';

//used
export const GET_AUTHOR_PRODUCT_REQUEST = 'products/GET_AUTHOR_PRODUCT_REQUEST';
export const GET_AUTHOR_PRODUCT_SUCCESS = 'products/GET_AUTHOR_PRODUCT_SUCCESS';
export const GET_AUTHOR_PRODUCT_FAILURE = 'products/GET_AUTHOR_PRODUCT_FAILURE';


//for admin only
export const ADD_PRODUCT_REQUEST = 'products/ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'products/ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'products/ADD_PRODUCT_FAILURE';

//for admin only
export const UPDATE_PRODUCT_REQUEST = 'products/UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'products/UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'products/UPDATE_PRODUCT_FAILURE';


export const UPDATE_PRODUCT_REQUEST1 = 'products/UPDATE_PRODUCT_REQUEST1';
export const UPDATE_PRODUCT_SUCCESS1 = 'products/UPDATE_PRODUCT_SUCCESS1';
export const UPDATE_PRODUCT_FAILURE1 = 'products/UPDATE_PRODUCT_FAILURE1';

//for admin only
export const DELETE_PRODUCT_REQUEST = 'products/DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'products/DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'products/DELETE_PRODUCT_FAILURE';

export const DELETE_OPPOINTMENT_REQUEST = 'products/DELETE_OPPOINTMENT_REQUEST';
export const DELETE_OPPOINTMENT_SUCCESS = 'products/DELETE_OPPOINTMENT_SUCCESS';
export const DELETE_OPPOINTMENT_FAILURE = 'products/DELETE_OPPOINTMENT_FAILURE';



export const GET_AUTHOR_PRODUCT_REQUEST1 = 'products/GET_AUTHOR_PRODUCT_REQUEST1';
export const GET_AUTHOR_PRODUCT_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT_SUCCESS2';
export const GET_AUTHOR_PRODUCT_FAILURE3 = 'products/GET_AUTHOR_PRODUCT_FAILURE3';
