export const GET_ALL_FAMILYDETAILS_REQUEST = 'products/GET_ALL_FAMILYDETAILS_REQUEST';
export const GET_ALL_FAMILYDETAILS_SUCCESS = 'products/GET_ALL_FAMILYDETAILS_SUCCESS';
export const GET_ALL_FAMILYDETAILS_FAILURE = 'products/GET_ALL_FAMILYDETAILS_FAILURE';

//on single product page
export const GET_SINGLE_FAMILY_REQUEST = 'products/GET_SINGLE_FAMILY_REQUEST';
export const GET_SINGLE_FAMILY_SUCCESS = 'products/GET_SINGLE_FAMILY_SUCCESS';
export const GET_SINGLE_FAMILY_FAILURE = 'products/GET_SINGLE_FAMILY_FAILURE';

//used
export const GET_DOCTOR_FAMILY_REQUEST = 'products/GET_DOCTOR_FAMILY_REQUEST';
export const GET_DOCTOR_FAMILY_SUCCESS = 'products/GET_DOCTOR_FAMILY_SUCCESS';
export const GET_DOCTOR_FAMILY_FAILURE = 'products/GET_DOCTOR_FAMILY_FAILURE';


//for admin only
export const ADD_MEMBER_FAMILY_REQUEST = 'products/ADD_MEMBER_FAMILY_REQUEST';
export const ADD_MEMBER_FAMILY_SUCCESS = 'products/ADD_MEMBER_FAMILY_SUCCESS';
export const ADD_MEMBER_FAMILY_FAILURE = 'products/ADD_MEMBER_FAMILY_FAILURE';

//for admin only
export const UPDATE_MEMBER_FAMILY_REQUEST = 'products/UPDATE_MEMBER_FAMILY_REQUEST';
export const UPDATE_MEMBER_FAMILY_SUCCESS = 'products/UPDATE_MEMBER_FAMILY_SUCCESS';
export const UPDATE_MEMBER_FAMILY_FAILURE = 'products/UPDATE_MEMBER_FAMILY_FAILURE';

//for admin only
export const DELETE_MEMBER_FAMILY_REQUEST = 'products/DELETE_MEMBER_FAMILY_REQUEST';
export const DELETE_MEMBER_FAMILY_SUCCESS = 'products/DELETE_MEMBER_FAMILY_SUCCESS';
export const DELETE_MEMBER_FAMILY_FAILURE = 'products/DELETE_MEMBER_FAMILY_FAILURE';

export const DELETE_OPPOINTMENT_REQUEST = 'products/DELETE_OPPOINTMENT_REQUEST';
export const DELETE_OPPOINTMENT_SUCCESS = 'products/DELETE_OPPOINTMENT_SUCCESS';
export const DELETE_OPPOINTMENT_FAILURE = 'products/DELETE_OPPOINTMENT_FAILURE';



export const GET_AUTHOR_PRODUCT_REQUEST1 = 'products/GET_AUTHOR_PRODUCT_REQUEST1';
export const GET_AUTHOR_PRODUCT_SUCCESS2 = 'products/GET_AUTHOR_PRODUCT_SUCCESS2';
export const GET_AUTHOR_PRODUCT_FAILURE3 = 'products/GET_AUTHOR_PRODUCT_FAILURE3';
